import { HttpClient, HttpParams } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { environment } from '../../environments/environment';
import { ProductionOrderDetail, ProductionOrderHeader, ProductionSession } from '../_models/productionOrder';

@Injectable({
  providedIn: 'root'
})
export class ManufacturingService {
  baseUrl = environment.apiUrl + '';

  constructor(private http: HttpClient) { }

  getProductionOrders(): Observable<ProductionOrderHeader[]> {
    return this.http.get<ProductionOrderHeader[]>(this.baseUrl + 'productionOrder').pipe(
      map(response => {
        // if (isFromOutlet != null) {
        // return response.filter(a => a.status === isFromOutlet);
        // }
        return response;
      }));

  }
  getProductionOrder(id): Observable<ProductionOrderHeader> {
    return this.http.get<ProductionOrderHeader>(this.baseUrl + 'productionOrder/' + id);
  }

  getProductionOrderDetailsOfHeader(id): Observable<ProductionOrderDetail[]> {
    return this.http.get<ProductionOrderHeader>(this.baseUrl + 'productionOrder/' + id).pipe(
      map(response => {
        return response.productionOrderDetails;
      }));
  }
  getAutoGeneratedProductionOrder(sessionId, placeId, requiredDate): Observable<ProductionOrderHeader> {
    let params = new HttpParams();
    params = params.append('sessionId', sessionId.toString());
    params = params.append('placeId', placeId.toString());
    params = params.append('requiredDate', requiredDate.toString());
    return this.http.get<ProductionOrderHeader>(this.baseUrl + 'productionOrder/GetAutoProductionOrder', { params });
  }
  createProductionOrder(productionOrder: ProductionOrderHeader) {
    // let params = new HttpParams();
    // params = params.append('isForSending', 'false');
    return this.http.post(this.baseUrl + 'productionOrder', productionOrder);
  }

  updateProductionOrder(id: number, productionOrder: ProductionOrderHeader) {
    // let params = new HttpParams();
    // params = params.append('isForSending', 'false');
    return this.http.put(this.baseUrl + 'productionOrder/' + id, productionOrder);
  }

  deleteProductionOrder(id: number) {
    return this.http.delete(this.baseUrl + 'productionOrder/' + id);
  }


  getProductionSessions(): Observable<ProductionSession[]> {
    return this.http.get<ProductionSession[]>(this.baseUrl + 'productionSessions');
  }
  getProductionSession(id): Observable<ProductionSession> {
    return this.http.get<ProductionSession>(this.baseUrl + 'productionSessions/' + id);
  }

}
